
Cd(__DIR__);;
#include "ConvertToTxt"

DirMake("~/Tmp");
CopyTree("../Pages","~/Tmp/Insecticide/Pages");
CopyTree("../Scripts","~/Tmp/Insecticide/Scripts");

CopyTree("../LevelSaves/SavesStory","~/Tmp/Insecticide/LevelSaves/SavesStory");
CopyTree("../LevelSaves/SavesChallenges","~/Tmp/Insecticide/LevelSaves/SavesChallenges");

CopyTree("../LevelScripts/SavesStory","~/Tmp/Insecticide/LevelScripts/SavesStory");
CopyTree("../LevelScripts/SavesChallenges","~/Tmp/Insecticide/LevelScripts/SavesChallenges");


//Convert to Txt
ConvertTreeToTxt("~/Tmp/Insecticide/Pages/Game/Actions");
ConvertTreeToTxt("~/Tmp/Insecticide/Pages/Game/Draw");
ConvertTreeToTxt("~/Tmp/Insecticide/Pages/Game");
ConvertTreeToTxt("~/Tmp/Insecticide/Pages/MapEditor");
ConvertTreeToTxt("~/Tmp/Insecticide/Pages");
ConvertTreeToTxt("~/Tmp/Insecticide/Scripts/ZealOSPort/OldLevels");
ConvertTreeToTxt("~/Tmp/Insecticide/Scripts/ZealOSPort");
ConvertTreeToTxt("~/Tmp/Insecticide/Scripts");

ConvertTreeToTxt("~/Tmp/Insecticide/LevelSaves/SavesStory");
ConvertTreeToTxt("~/Tmp/Insecticide/LevelSaves/SavesChallenges");

ConvertTreeToTxt("~/Tmp/Insecticide/LevelScripts/SavesStory");
ConvertTreeToTxt("~/Tmp/Insecticide/LevelScripts/SavesChallenges");


Copy("../Here.ZC.Z","~/Tmp/Insecticide/Here.TXT");
Copy("../RunGame.ZC.Z","~/Tmp/Insecticide/Run.TXT");

Copy("../misc/README.DD.Z","~/Tmp/Insecticide/misc/README.DD");
Copy("../misc/UpdateLogs.DD.Z","~/Tmp/Insecticide/misc/UpdateLogs.DD");

Copy("../misc/README.DD.Z","~/Tmp/README.DD");
Copy("ZealOSPort/AutoInstallZeal.ZC.Z","~/Tmp/AutoInstallZeal.ZC");
Copy("AutoInstallTOS.ZC.Z","~/Tmp/AutoInstallTOS.ZC.Z");


CopyTree("~/Tmp","Q:/");
DelTree("~/Tmp");
